---
- name: install beanstalkd
  yum: name=beanstalkd state=present
  tags:
    - beanstalkd
    - packages

- name: configure beanstalkd
  template: src=sysconfig.j2 dest=/etc/sysconfig/beanstalkd owner=root group=root mode=0644
  notify: restart beanstalkd
  tags:
    - beanstalkd
    - configuration

- name: ensure beanstalkd is enabled and running
  service: name=beanstalkd enabled=yes state=started
  tags:
    - beanstalkd
    - configuration
    - services

- name: configure firewalld for beanstalkd
  firewalld: zone=public port="{{ beanstalkd_port }}/tcp" permanent=true state=enabled
  notify: reload firewall
  when: beanstalkd_open_port and ansible_distribution_major_version|int > 6
  tags:
    - beanstalkd
    - firewall
    - configuration